shellcheck fixes, v0.4

diff --git a/src/soap b/src/soap
--- a/src/soap
+++ b/src/soap
@@ -9,7 +9,7 @@
 # ARG_HELP([The general script's help msg])
 # ARGBASH_GO
 
-soap_cli_version="v0.3"
+soap_cli_version="v0.4"
 
 die()
 {
@@ -36,21 +36,37 @@ _arg_dry=
 
 _curl_options=
 
-xml_update=
-
 print_help()
 {
 	printf '%s\n' "soap-cli $soap_cli_version" 
 	printf "Send SOAP messages from command line. \n"
-	printf 'Usage: %s <endpoint> <request> [-u|--update <arg>] [-v|--value <arg>] [-d|--dry] [-h|--help] [--version] [curl options] \n' "$0"
+	printf 'Usage: soap <endpoint> <request> [-u|--update <arg>] [-v|--value <arg>] [-d|--dry] [-h|--help] [--version] [curl options] \n'
 	printf '\t%s\n' "<endpoint>: SOAP endpoint url"
 	printf '\t%s\n' "<request>: SOAP request file"
-	printf '\t%s\n' "-u, --update: update the the value by given XPath; valid only with value option (no default)"
-	printf '\t%s\n' "-v, --value: update the the value by given XPath; valid only with update option (no default)"
+	printf '\t%s\n' "-u, --update: update the the value by given XPath; valid only with --value option"
+	printf '\t%s\n' "-v, --value: update the the value by given XPath; valid only with --update option"
 	printf '\t%s\n' "-d, --dry: dry run, prints the curl command but do not execute"
 	printf '\t%s\n' "-h, --help: Prints help"
 	printf '\t%s\n' "--version: Prints version number"
-	printf '\t%s\n' "All additional arguments and options passed to curl. (curl --help all)"
+	printf '\t%s\n' "All additional arguments and options passed to curl. (see 'curl --help all')"
+	check_requirements
+}
+
+check_requirements()
+{
+  if ! command -v xmlstarlet &> /dev/null
+  then
+      printf "\nWARNING! xmlstarlet could not be found! --update and --value options will not work properly\n"
+      printf "You can install xmlstarlet with one of the following commands:\n\n"
+      printf "Ubuntu\n"
+      printf "sudo snap install xmlstarlet\n\n"
+      printf "MacOS\n"
+      printf "brew install xmlstarlet\n\n"
+      printf "cygwin\n"
+      printf "apt-cyg install xmlstarlet\n"
+      exit
+  fi
+
 }
 
 print_version()
@@ -118,24 +134,20 @@ handle_passed_args_count()
 {
 	local _required_args_string="'endpoint' and 'request'"
 	test "${_positionals_count}" -ge 2 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
-	#test "${_positionals_count}" -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
 }
 
 
 assign_positional_args()
 {
 	local _positional_name _shift_for=$1
-	_positional_names="_arg_endpoint _arg_request "
-
 	shift "$_shift_for"
-	for _positional_name in ${_positional_names}
-	do
-		test $# -gt 0 || break
-		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
-		shift
-	done
- 
 
+  _arg_endpoint=$1
+  shift
+  _arg_request=$1
+  shift
+
+  #all additional args are curl args
 	while [ "${1}" != "" ]; do
 		_curl_options="$_curl_options ${1}"
 		shift
@@ -146,17 +158,18 @@ assign_positional_args()
 
 handle_otpional_args()
 {
-	if ([ "$_arg_update" == "" ] && [ "$_arg_value" != "" ])
+  xml_update_needed="false"
+	if [ "$_arg_update" == "" ] && [ "$_arg_value" != "" ]
 	then
 		die "--update and --value arguments only make sense together" 1
 	fi
 
-	if ([ "$_arg_update" != "" ] && [ "$_arg_value" == "" ])
+	if [ "$_arg_update" != "" ] && [ "$_arg_value" == "" ]
 	then
 		die "--update and --value arguments only make sense together" 1
 	fi
 
-	if ([ "$_arg_update" != "" ] && [ "$_arg_value" != "" ])
+	if [ "$_arg_update" != "" ] && [ "$_arg_value" != "" ]
 	then
 		xml_update_needed="true"
 	fi
@@ -165,27 +178,27 @@ handle_otpional_args()
 soap_call()
 {
 	file="$_arg_request"
-	if ([ "$xml_update_needed" != "" ])
+	if [ "$xml_update_needed" == "true" ]
 	then
 		file='soap_cli_template.xml'
 	fi
 
 	curl_command="curl -s $_curl_options --request POST --header 'Content-Type: text/xml;charset=UTF-8' -d @$file $_arg_endpoint"
 
-	if ([ "$_arg_dry" == "true" ])
+	if [ "$_arg_dry" == "true" ]
 	then
 		echo "$curl_command"
-	elif eval $curl_command | xmllint --encode UTF8 --format - 2>/dev/null
+	elif eval "$curl_command" | xmllint --encode UTF8 --format - 2>/dev/null
 	then
 		return
 	else 
-		eval $curl_command
+		eval "$curl_command"
 	fi
 }
 
 update_xml()
 {
-	if ([ "$xml_update_needed" != "" ])
+	if [[ "$xml_update_needed" == "true" ]]
 	then
 		xmlstarlet edit --update "$_arg_update" --value "$_arg_value"  "$_arg_request" > soap_cli_template.xml
 	fi
@@ -193,7 +206,7 @@ update_xml()
 
 clean_up()
 {
-	if ([ "$xml_update_needed" != "" ])
+	if [[ "$xml_update_needed" == "true" ]]
 	then
 		rm soap_cli_template.xml
 	fi
